name: Create a tag on main push

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: Create the next semver tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          default_bump: false
          default_prerelease_bump: false
          # Use custom PAT token instead of GITHUB_TOKEN if you trigger subsequent workflows!
          # https://stackoverflow.com/questions/67550727/push-event-doesnt-trigger-workflow-on-push-paths-github-actions
          github_token: ${{ secrets.GITHUB_TOKEN }}
